### ISSUE TITLE
Error at Testing

### ISSUE THREAD

**Issue by mardimitr** [privacybydesign/irma_api_server#15]
Hello!
I use ubuntu 16.04 and installed java 1.8.0_161 and gradle-4.6 .
I tried to build the irma_api_server and I followed the guide. However, I tried to test it and I used the command **node utils/testsp.js http://localhost:8088** but I got he following error:
**fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open 'irma_api_server/pk.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/ias/irma_api_server/utils/testsp.js:31:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)**

Should I execute other command ? How can I deal with this ?

Thanks a lot!

**Comment by sietseringers** [comment]
Hi!

I can't be sure exactly what is going wrong, but the script seems to fail to find the public key with which the API server signs its responses. It is checking for it at `irma_api_server/pk.pem`, which is wrong, as it is generally located at `src/main/resources/pk.pem`.

There are several confusing things about the error:
- the stack trace points to line 31 of `testsp.js`, but the loading of the public key [happens at line 30](https://github.com/privacybydesign/irma_api_server/blob/master/utils/testsp.js#L30), and there has never been a version where that happens at line 31
- as I mentioned, the path is wrong. The only way that the script would look at a location different from the one I mentioned is by passing it a third parameter, but you have not done so.

Have you perhaps modified the testsp.js script? Are you on the latest `master`?

**Comment by mardimitr** [comment]
Thank you very much for your response!
I don't change the file and I use the latest version of the master.
I built it again but at this time I executed the command **node utils/testsp.js http://localhost:8088** and I got the following different result:
eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzcHJlcXVlc3QiOnsidmFsaWRpdHkiOjYwLCJ0aW1lb3V0Ijo2MCwicmVxdWVzdCI6eyJjb250ZW50IjpbeyJsYWJlbCI6Ik92ZXIgMjEiLCJhdHRyaWJ1dGVzIjpbImlybWEtZGVtby5NaWpuT3ZlcmhlaWQuYWdlTG93ZXIub3ZlcjE4IiwiaXJtYS1kZW1vLk1pam5PdmVyaGVpZC5hZ2VMb3dlci5vdmVyMjEiXX1dfX0sImlhdCI6MTUyMDk1MDgzNiwiaXNzIjoidGVzdHNwIiwic3ViIjoidmVyaWZpY2F0aW9uX3JlcXVlc3QifQ.
**Error in initial request:
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 503 </title>
</head>
<body>
<h2>HTTP ERROR: 503</h2>
<p>Problem accessing /irma_api_server/api/v2/verification/. Reason:
<pre>    Service Unavailable</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>**

It is not the same with the first problem. How can I deal with this ?
Thank you very much for your time and help.

**Comment by sietseringers** [comment]
That looks more familiar. Probably it means that the irma_api_server encountered some error during startup (e.g. missing `irma_configuration` folder in `src/main/resources`), so that it cannot handle the request that testsp.js sent to it. When you start irma_api_server, does it output an exception?
