### ISSUE TITLE
Internal server error on websocket connection to demo server in sign demo

### ISSUE THREAD

**Issue by hidde-jan** [privacybydesign/irma_api_server#18]
I tried to follow the signing demo at https://demo.irmacard.org/tomcat/irma_api_server/examples/sign.html, but it seems the websocket handshake goes wrong. I'm receiving a 500 internal server error response.

**Comment by hidde-jan** [comment]
Hi Sietse, long time no see 😄 

Yeah polling is working for me, so the IRMA sessions themselves work fine. I just thought I would notify you in case it wasn't a known issue.

**Comment by sietseringers** [comment]
Thanks for that 🙂
