### ISSUE TITLE
CORS enabling on docker image

### ISSUE THREAD

**Issue by marc4gov** [privacybydesign/irma_api_server#32]
Trying to make a client React app, I get CORS issues. Is there any way I can tune a docker file in order to avoid this?
I started the IRMA-api-server with the provided docker image. Command line tests went fine.
See log:

<img width="535" alt="schermafbeelding 2019-01-20 om 16 03 14" src="https://user-images.githubusercontent.com/9572139/51440990-2f5ce000-1ccd-11e9-88b1-5652c876972c.png">

**Comment by davidv1992** [comment]
Ok I see what the problem is. You need to intialize irma_js with http://localhost:8088/api/v2/, as that is the path where the server listens to by default. On the other location you just get a generic 404/400 error that does not include CORS headers.
